-- 🔑 Keywords: Credentials AI Lead Engine v1, business_profiles, profile_sessions, profile_views, lead_events, tracked enquiries, quote form, lead attribution
-- Credentials AI Lead Engine v1 database foundation
-- Date: 2026-07-09
-- Scope: additive, replay-safe schema for first tracked enquiry sprint.

BEGIN;

-- ---------------------------------------------------------------------------
-- Utility
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.credentials_ai_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- business_profiles: canonical public lead profile records
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.business_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  source_page_id uuid NULL REFERENCES public.pages(id) ON DELETE SET NULL,
  trustbadge_id uuid NULL REFERENCES public.trustbadges(id) ON DELETE SET NULL,
  slug text NOT NULL UNIQUE,
  business_name text NOT NULL,
  abn text,
  abn_status text NOT NULL DEFAULT 'unverified',
  category text,
  description text,
  phone text,
  email text,
  website text,
  suburb text,
  state text,
  postcode text,
  service_areas jsonb NOT NULL DEFAULT '[]'::jsonb,
  services jsonb NOT NULL DEFAULT '[]'::jsonb,
  social_links jsonb NOT NULL DEFAULT '{}'::jsonb,
  plan text NOT NULL DEFAULT 'free',
  verification_level integer NOT NULL DEFAULT 0,
  booking_url text,
  logo_url text,
  hero_image_url text,
  status text NOT NULL DEFAULT 'active',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT business_profiles_slug_nonempty CHECK (length(trim(slug)) > 0),
  CONSTRAINT business_profiles_business_name_nonempty CHECK (length(trim(business_name)) > 0),
  CONSTRAINT business_profiles_abn_status_check CHECK (abn_status IN ('unverified', 'verified', 'mismatch', 'not_found', 'pending')),
  CONSTRAINT business_profiles_plan_check CHECK (plan IN ('free', 'verified_pro', 'founder', 'admin')),
  CONSTRAINT business_profiles_verification_level_check CHECK (verification_level BETWEEN 0 AND 5),
  CONSTRAINT business_profiles_status_check CHECK (status IN ('active', 'draft', 'paused', 'archived'))
);

CREATE INDEX IF NOT EXISTS idx_business_profiles_status_created_at
  ON public.business_profiles (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_business_profiles_owner_user_id
  ON public.business_profiles (owner_user_id);

CREATE INDEX IF NOT EXISTS idx_business_profiles_source_page_id
  ON public.business_profiles (source_page_id);

CREATE INDEX IF NOT EXISTS idx_business_profiles_trustbadge_id
  ON public.business_profiles (trustbadge_id);

CREATE INDEX IF NOT EXISTS idx_business_profiles_plan
  ON public.business_profiles (plan);

DROP TRIGGER IF EXISTS business_profiles_set_updated_at ON public.business_profiles;
CREATE TRIGGER business_profiles_set_updated_at
  BEFORE UPDATE ON public.business_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.credentials_ai_set_updated_at();

-- ---------------------------------------------------------------------------
-- profile_sessions: attribution session for public profile visitors
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profile_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_profile_id uuid REFERENCES public.business_profiles(id) ON DELETE SET NULL,
  source text,
  medium text,
  referrer text,
  landing_path text,
  device_type text,
  ip_hash text,
  user_agent_class text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profile_sessions_business_profile_id_created_at
  ON public.profile_sessions (business_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profile_sessions_source_created_at
  ON public.profile_sessions (source, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profile_sessions_created_at_desc
  ON public.profile_sessions (created_at DESC);

-- ---------------------------------------------------------------------------
-- profile_views: page/view proof events
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profile_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_profile_id uuid REFERENCES public.business_profiles(id) ON DELETE SET NULL,
  session_id uuid REFERENCES public.profile_sessions(id) ON DELETE SET NULL,
  path text,
  source text,
  referrer text,
  is_bot boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_profile_views_business_profile_id_created_at
  ON public.profile_views (business_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profile_views_session_id_created_at
  ON public.profile_views (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profile_views_source_created_at
  ON public.profile_views (source, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_profile_views_created_at_desc
  ON public.profile_views (created_at DESC);

-- ---------------------------------------------------------------------------
-- lead_events: quote/call/email/booking/badge/QR events
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.lead_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_profile_id uuid REFERENCES public.business_profiles(id) ON DELETE SET NULL,
  session_id uuid REFERENCES public.profile_sessions(id) ON DELETE SET NULL,
  type text NOT NULL,
  source text,
  referrer text,
  name text,
  phone text,
  email text,
  suburb text,
  service_needed text,
  message text,
  status text NOT NULL DEFAULT 'new',
  first_response_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lead_events_type_check CHECK (type IN ('quote_form', 'call_click', 'email_click', 'booking_click', 'qr_scan', 'badge_click', 'quote_form_open')),
  CONSTRAINT lead_events_status_check CHECK (status IN ('new', 'contacted', 'quoted', 'won', 'lost', 'spam'))
);

CREATE INDEX IF NOT EXISTS idx_lead_events_business_profile_id_created_at
  ON public.lead_events (business_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_events_session_id_created_at
  ON public.lead_events (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_events_type_created_at
  ON public.lead_events (type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_events_status_created_at
  ON public.lead_events (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_lead_events_source_created_at
  ON public.lead_events (source, created_at DESC);

DROP TRIGGER IF EXISTS lead_events_set_updated_at ON public.lead_events;
CREATE TRIGGER lead_events_set_updated_at
  BEFORE UPDATE ON public.lead_events
  FOR EACH ROW
  EXECUTE FUNCTION public.credentials_ai_set_updated_at();

-- ---------------------------------------------------------------------------
-- Initial backfill: turn existing SchemaPage `pages` into business profiles.
-- This lets /b/[slug] and lead tracking ship against current customer records.
-- ---------------------------------------------------------------------------

INSERT INTO public.business_profiles (
  source_page_id,
  slug,
  business_name,
  description,
  phone,
  email,
  website,
  service_areas,
  services,
  social_links,
  plan,
  status,
  metadata,
  created_at,
  updated_at
)
SELECT
  p.id,
  p.slug,
  p.business_name,
  p.description,
  p.contact_phone,
  COALESCE(p.contact_email, p.creator_email),
  p.website_url,
  CASE
    WHEN p.location_address IS NULL OR trim(p.location_address) = '' THEN '[]'::jsonb
    ELSE jsonb_build_array(p.location_address)
  END,
  COALESCE(p.services, '[]'::jsonb),
  COALESCE(p.social_links, '{}'::jsonb),
  CASE WHEN p.is_pro THEN 'verified_pro' ELSE 'free' END,
  'active',
  jsonb_build_object(
    'imported_from', 'pages',
    'tagline', p.tagline,
    'brand_color', p.brand_color,
    'creator_email', p.creator_email,
    'location_address', p.location_address
  ) || COALESCE(p.metadata, '{}'::jsonb),
  COALESCE(p.created_at, now()),
  COALESCE(p.updated_at, now())
FROM public.pages p
WHERE NOT EXISTS (
  SELECT 1 FROM public.business_profiles bp WHERE bp.slug = p.slug
);

-- ---------------------------------------------------------------------------
-- RLS + grants
-- Server/API uses service role for v1. Keep visitor data private by default.
-- ---------------------------------------------------------------------------

ALTER TABLE public.business_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_profiles_service_role_all ON public.business_profiles;
CREATE POLICY business_profiles_service_role_all
  ON public.business_profiles
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS profile_sessions_service_role_all ON public.profile_sessions;
CREATE POLICY profile_sessions_service_role_all
  ON public.profile_sessions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS profile_views_service_role_all ON public.profile_views;
CREATE POLICY profile_views_service_role_all
  ON public.profile_views
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS lead_events_service_role_all ON public.lead_events;
CREATE POLICY lead_events_service_role_all
  ON public.lead_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON public.business_profiles FROM anon, authenticated;
REVOKE ALL ON public.profile_sessions FROM anon, authenticated;
REVOKE ALL ON public.profile_views FROM anon, authenticated;
REVOKE ALL ON public.lead_events FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.business_profiles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profile_sessions TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profile_views TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lead_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
